<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<ImplicitUsings>enabled</ImplicitUsings>
    <RootNamespace>DouglasDwyer.PowerSerializer</RootNamespace>
    <AssemblyName>DouglasDwyer.PowerSerializer</AssemblyName>
    <Authors>Douglas Dwyer</Authors>
    <Company>Douglas Dwyer</Company>
    <Product>PowerSerializer</Product>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Description>PowerSerializer is a fast, efficient, customizable C# binary serializer that can serialize absolutely anything.</Description>
    <PackageProjectUrl>https://github.com/DouglasDwyer/PowerSerializer</PackageProjectUrl>
    <RepositoryUrl>https://github.com/DouglasDwyer/PowerSerializer</RepositoryUrl>
    <RepositoryType>GitHub</RepositoryType>
    <NeutralLanguage>en</NeutralLanguage>
    <AssemblyVersion>2.0.0</AssemblyVersion>
    <FileVersion>2.0.0</FileVersion>
	<Version>2.0.0</Version>
	<PackageReleaseNotes></PackageReleaseNotes>
	<PackageTags>serialization csharp binary collections arrays polymorphism serialization-library csharp-library</PackageTags>
	<Nullable>enable</Nullable>
	<WarningsAsErrors>Nullable</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="5.0.0" />
    <PackageReference Include="System.IO.Hashing" Version="9.0.10" />
  </ItemGroup>
</Project>
